---
# tasks file for letsencrypt-certs
- name: Show early certificates
  debug:
    msg: "Certificates is {{ certificates | list }}"
    verbosity: 4
  when: certificates is defined

- name: Show early certificate services
  debug:
    msg: "Certificate services is {{ certificate_services | list }}"
    verbosity: 4
  when: certificate_services is defined

- name: Merge certificates
  merge_vars:
    suffix_to_merge: certificates__to_merge
    merged_var_name: certificates
    cacheable: false
    expected_type: 'list'
    warn: false

- name: Merge certificate_services
  merge_vars:
    suffix_to_merge: certificate_services__to_merge
    merged_var_name: certificate_services
    cacheable: false
    expected_type: 'list'

- include_tasks: push-certificates.yml
  when:
    - certificates is defined
    - ( certificates | default([]) ) | length > 0

...
