---
# tasks file for letsencrypt-certs
- name: Debug
  vars:
    msg: |
       Inventory Hostname:
       {{ inventory_hostname }}

       Module Variables ("vars"):
       --------------------------------
       {{ vars | to_nice_json }}

       Environment Variables ("environment"):
       --------------------------------
       {{ environment | to_nice_json }}

       GROUP NAMES Variables ("group_names"):
       --------------------------------
       {{ group_names | to_nice_json }}

       GROUPS Variables ("groups"):
       --------------------------------
       {{ groups | to_nice_json }}

       HOST Variables ("hostvars"):
       --------------------------------
       {{ hostvars | to_nice_json }}

  debug:
    msg: "{{ msg.split('\n') }}"
    verbosity: 5

- name: testing
  debug:
    msg: "Certificates is {{ certificates | list }}"
  when: certificates is defined

- name: template
  synchronize:
    mode: push
    src: /etc/letsencrypt/
    dest: /etc/letsencrypt/
    copy_links: true
    rsync_opts: "{{ lookup('template', 'rsync_opts.j2') | from_yaml }}"
  when: certificates is defined
...
